[tool.poetry]
name = "lysia"
version = "2024.1.0"
description = "A Discord API wrapper in python."
authors = ["SubeCraft"]
license = "MIT"
readme = "README.md"

homepage = "https://github.com/SubeCraft/Lysia"
repository = "https://github.com/SubeCraft/Lysia"

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed"
]

packages = [{include = "lysia"}]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/SubeCraft/Lysia/issues"

[tool.poetry.dependencies]
python = "^3.12"

httpx = "^0.27.0"
pydantic = "^2.7.1"
loguru = "^0.7.2"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.12.2"
ruff = "^0.3.7"
pyright = "^1.1.360"

[tool.taskipy.settings]
runner = "poetry run"

[tool.taskipy.tasks]
lint = {cmd = "ruff check lysia --fix -e && pyright", help = "Lint, Format & Type Check the project."}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
