LIBRARY_NAME = "Lysia"
LIBRARY_VERSION = "2023.1.0"

DISCORD_API_ENDPOINT = "https://discord.com/api"
DISCORD_API_VERSION = 10
DISCORD_API_URL = f"{DISCORD_API_ENDPOINT}/v{DISCORD_API_VERSION}"

DISCORD_CDN_ENDPOINT = "https://cdn.discordapp.com"
